version: '3.7'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    expose: [6379]
  routr-eet:
    build:
      context: .
    image: fonoster/routr-eet:latest
    expose: [5061]
    entrypoint: |
      sh -c '
          while ! nc -z routr 4567 > /dev/null 2>&1; do sleep 0.1; done # Wait for Routr
          cd tests && npm install && npm test
          node stop_dut.js
      '
    env_file: .env
    volumes:
      - .:/tests
  routr:
    links:
      - "routr-eet:sip.provider.net"
    image: fonoster/routr:latest
    entrypoint: sh -c '/opt/routr/wait-for-it.sh redis:6379 -- ./routr'
    environment:
      ROUTR_EXTERN_ADDR: ${ROUTR_EXTERN_ADDR}
      ROUTR_DS_PROVIDER: redis_data_provider
      ROUTR_DS_PARAMETERS: host=redis,port=6379
    expose: [4567, 5060]
    volumes:
      - ./etc/wait-for-it.sh:/opt/routr/wait-for-it.sh:ro
  routr-provision:
    build:
      context: .provisioner
    entrypoint: |
      sh -c '
        while ! nc -z routr 4567 > /dev/null 2>&1; do sleep 0.1; done # Wait for Routr
        rctl login https://routr:4567/api/v1beta1 -u admin -p changeit
        rctl create -f /opt/routr/bootstrap.yml
      '
    volumes:
      - ./etc/bootstrap.yml:/opt/routr/bootstrap.yml:ro
