name: eet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: docker-compose up --abort-on-container-exit --exit-code-from routr-eet
