name: eet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        env:
          ROUTR_EXTERN_ADDR: 127.0.0.1
        run: docker-compose up --abort-on-container-exit --exit-code-from routr-eet
