name: publish to docker hub
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1      
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@v5 
        with:
          name: fonoster/seet
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: .
          tags: "latest, ${{ steps.package-version.outputs.current-version }}"
          platforms: linux/amd64,linux/arm64
